# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addjob',
            name='post_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
