# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20171008_2234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addJob',
            new_name='Occupation',
        ),
    ]
